### ISSUE TITLE
[Bug]: ignore_incoming ignore routed packages, can't be used for testing

### ISSUE THREAD

**Issue by khrystynaO** [meshtastic/firmware#2343]
### Category

Other

### Hardware

T-Beam

### Firmware Version

2.0.23.7bb281d

### Description

When we set nodenum in config ignore_incoming list  - device ignores all types of packets including routed ones. 

What can we use for debugging routing packages through a third device?

**Comment by garthvh** [comment]
Ignore incoming will indeed artificially drop all packets from that node, have you used the trace route function?  That is the only way currently to track packets across nodes.

**Comment by khrystynaO** [comment]
What is the correct way to implement this feature?

**Comment by GUVWAF** [comment]
How to use the Traceroute is documented [here](https://meshtastic.org/docs/settings/moduleconfig/traceroute). 
Not ignoring routed packets would require breaking changes, because Meshtastic normally does not keep track of the ID of a node that is only rebroadcasting/relaying a message. A routed packet is an exact copy of the original one, except for the hop limit, which is bumped down by one.
