### ISSUE TITLE
[Usability]: Use 255 as value to indicate maximum power, instead of 0

### ISSUE THREAD

**Issue by S5NC** [meshtastic/firmware#2931]
### Platform

NRF52, ESP32

### Description

Setting power to 0 [dBm] should set radio output to 0 [dBm], as 0 dBm is a value which may be desired if using an external PA, or for testing with a spectrum analyser. 1 results in 1 being set, -1 results in -1, but 0 currently results in values as high as 22, depending on the radio IC. 255 [dBm] is clearly not a power setting that will never be valid in any radio IC's power configuration (assuming it's in dBm not W nor mW!), and 255 is used [here](https://github.com/meshtastic/firmware/blob/master/src/mesh/RadioInterface.cpp#L499) already.

If 0 is actually sent in protobufs (there was some uncertainity about this), then this would be a breaking change, if not, it wouldn't be.

**Comment by garthvh** [comment]
There is no uncertainty, 0 is default in protobufs, which in this case is 30 and then set independently for each radio.

**Comment by JmCasler** [comment]
@S5NC WIth protobufs, 0 is always the default value and is transmitted "Free" when serialized over the protocol. This means a value of 0 doesn't consume bits over the air. We made a conscious decision to use this as a core tenant of our protocol and like you indicate, it is a usability problem. Alas, it's one that we accept due to the nature of the limitations in our transport layer (lora's available bandwidth).

In protobufs version 3 (the version we use) doesn't have the ability to predefine the value of an unset variable, so we have to work with what's there.

I hope this helps you understand our design decision.

Please keep those ideas coming!

**Comment by garthvh** [comment]
I think you need to dig into protobufs some more
