### ISSUE TITLE
[Bug]: TFT Screens don't honor the flip screen display config value

### ISSUE THREAD

**Issue by garthvh** [meshtastic/firmware#3101]
### Category

Hardware Compatibility

### Hardware

T-Watch

### Firmware Version

2.2.18

### Description

I need to flip my twatch screen and the flip screen vertically config option is not doing anything.

**Comment by mverch67** [comment]
The issue appears in 2.2.17 where the following changes were made:
![image](https://github.com/meshtastic/firmware/assets/71137295/2a0b9c54-eff7-4750-908d-408f5d879c9e)

While it looks nice and clean to use the baseclass pointer it unfortunately does not work anymore, because the OLEDDisplay baseclass is poorly designed as it does not use virtual function declarations (especially in this case `flipScreenVertically()`). That means now `OLEDDisplay::flipScreenVertically()` is called instead of `TFTDisplay::flipScreenVertically()`.

There are two solutions:
(1) revert this change (but use pointers as required now in this commit)
(2) Change the library OLEDDisplay to use virtual function declarations (e.g. fork to meshtastic)

@jp-bennett
