### ISSUE TITLE
[Feature Request]: Reply Module 

### ISSUE THREAD

**Issue by gala-vine** [meshtastic/firmware#3348]
### Platform

NRF52, ESP32

### Description

Would be an excellent feature to have access to or edit the reply module (replymodule.cpp).. since there's no module for an auto response, it would be nice to make one, in an answer machine sort of sense when users are away from base nodes etc.

additionally and probably won't be added as a feature
it would be pretty interesting to see how far this could be pushed with integration with say Chatgpt or another A.I bot that could reply and take messages for you..

**Comment by smurfy** [comment]
Hi, while this issue is closed, i would be also interested in a auto-responder module. 

And i'm happy to take a crack at adding it.  (FW/iOS/Android)

Here  my use-case would be more for solar nodes which are not activly monitored and S&F is not really wanted.
Idea would be:

* Defineable message, like "This is an autonomous solar node, if you want to contact my owner please write to SHRT"
* Internal rolling list of last 10 or so nodes, so we only reply to new messages

Should i open a new issue? Has something like this even potential to beeing merged?
