### ISSUE TITLE
[Feature Request]: Configure Hop Limit Per Channel

### ISSUE THREAD

**Issue by David-Woodward** [meshtastic/firmware#3522]
### Platform

NRF52, ESP32

### Description

Would it be possible to make hop limit configurable per channel?

With the current global hop limit under LoRa config, our only choice is to go with the highest hop limit necessary to reach all the nodes in our channel.  Unfortunately this means if we want to chat in a channel with distant relatives that can only be reached through 5 hops, we also have to use a 5+ hop limit in LongFast and everywhere else.  Conversely, messages sent in a channel for neighborhood chat that could easily use a 1 hop limit also gets broadcast all over the wider mesh even though the nodes in that channel were likely reached directly with zero hops.

**Comment by thebentern** [comment]
Added this to the 3.0 project board, so I'm going to close it here.

**Comment by sahlstra** [comment]
This feature is currently drafted on the 3.0 roadmap but I'd like to make the case for pulling it into 2.x.

The implementation scope is narrow: a single field addition to ChannelSettings in the protobuf, with corresponding logic to use the per-channel hop limit when set, falling back to the global LoRa config value when not. This does not require architectural changes and fits cleanly within the existing 2.x channel configuration model.

The use case is concrete. Community mesh networks like MeshOregon configure a primary channel for wide-area communication and a secondary "Local" channel intended for nearby nodes. Without per-channel hop limits, the Local channel distinction is purely cosmetic. Messages propagate just as far as the primary channel, generating unnecessary airtime and defeating the intent. A hop limit of 1-2 on a secondary channel would give it genuine geographic scope.

This is a low-complexity, high-value change that would make multi-channel configurations semantically meaningful rather than just conventionally differentiated. Deferring it to 3.0 seems like inertia rather than a deliberate architectural decision. Would the maintainers consider pulling this into 2.x?
