### ISSUE TITLE
[Board]: Sparkfun MicroMod

### ISSUE THREAD

**Issue by Marx1** [meshtastic/firmware#3682]
### SOC

ESP32

### Lora IC

SX1276 

### Product Link

https://www.sparkfun.com/products/18573

### Description

This board is for a Sparkfun Micromod w/ a ESP32, and a 1w Lora module. Each of the parts are here:

Lora Module: https://www.sparkfun.com/products/18573
esp32 proccessor: https://www.sparkfun.com/products/16781
Micromod motherboard: https://www.sparkfun.com/products/20748 or https://www.sparkfun.com/products/20595

If you use a double main board, you can add GLNSS/GPS with this module: https://www.sparkfun.com/products/18378

This is mainly targeted for amateur radio mode, or repeater use where you need extra power to counteract coax/filter line losses. By utilizing the tx power adjustment you can ensure FCC Part 15 rules are met.

I currently have this active on my roof in a box with some other amateur radio stuff.

**Comment by thebentern** [comment]
Will accept PRs for this one if anyone wants to get it running but we won't be adding mainline support for it. The 915M30S is no longer manufactured and it performs poorly due to the underlying SX1276 board. The updated 900M30S which is used on the Hydra as well as other diy targets is a better LoRA radio option, as it utilizes the SX1262
