### ISSUE TITLE
[Feature Request]: Request node info when not in node list and message delivered

### ISSUE THREAD

**Issue by mzac** [meshtastic/firmware#3958]
### Platform

NRF52, ESP32, RP2040, Linux Native

### Description

I have noticed that if for example I'm in a new area and send a message to the Primary long fast channel, if a node is nearby and ACKs my message but they don't show up in the node list since they have not sent their node info.  Could my node then send a request node info packet and have the remote node broadcast their node info so it would show up in the node list?

Thanks

**Comment by thebentern** [comment]
This actually already happens when we encounter a message from a node we don't know, but there are multiple factors that can prevent it from happening, such as the 5 minute cooldown period for sending nodeinfo responses or the two nodes not sharing any common channel keys (but still benefiting from an an implicit ack rebroadcast).
