### ISSUE TITLE
[Feature Request]: some ideas for next releases ?

### ISSUE THREAD

**Issue by jranma** [meshtastic/firmware#4159]
### Platform

ESP32

### Description

Hey, here is a short wish list :-)

- Allow several clients to be connected to the same device, and for messages received or sent to be synchronised between all the clients.
- debug the traceroute tool, which most of the time doesn’t work (perhaps linked to MQTT)
- add a simple PING utility, with display of response time
- tool for visualising mesh topology and the quality of links between nodes

**Comment by GUVWAF** [comment]
- This is probably not going to be implemented on the microcontroller targets, might be something for Linux Native.
- There's not really something to "debug" about the traceroute tool. It has been proven to work endlessly (I have seen screenshots of traceroutes of 5, 6 and even 7 hops), but you have to have a stable two-way connection, just like acknowledgments on direct messages. There is only [0-hop reliability](https://meshtastic.org/docs/overview/mesh-algo/#layer-2-reliable-zero-hop-messaging), so if one transmission on the route gets corrupted due to e.g. a collision, there won't be an answer.
- This is not really a firmware request. E.g. the iOS app already shows the time an acknowledgment for a direct message has been received.
- Work-in-progress for that is here: https://github.com/meshtastic/network-management-client
