### ISSUE TITLE
[Feature Request]: Cannot Change Time Zone

### ISSUE THREAD

**Issue by uguraltinsoy** [meshtastic/firmware#4533]
### Platform

ESP32

### Description

When displaying the GPS instant time, it appears as GMT-0 time, we use GMT-3 in my country, how can I show it as GMT-3?

![WhatsApp Image 2024-08-22 at 16 02 54](https://github.com/user-attachments/assets/3b3aaba4-71cd-452c-a6a2-f3a6b9ca48e0)

**Comment by uguraltinsoy** [comment]
> There is a setting under device config

Can you explain in more detail please

**Comment by ponzano** [comment]
> > There is a setting under device config
> 
> 
> 
> Already set according to GMT-3 but it doesn't look like this on the oled screen
> 
> 
> 
> ![WhatsApp Image 2024-08-22 at 16 15 39](https://github.com/user-attachments/assets/a281d14c-64e1-41bf-ad08-3a16d4e71fa1)
> 
> 

I think it only works if you use this format 
https://stackoverflow.com/questions/73935736/time-zone-format

https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html

So for you it should be

CET-5CEST,M3.5.0/2:00:00,M10.4.0/3:00:00

Since Central European time is 2h ahead of gmt + your 3 hour difference from gmt
