### ISSUE TITLE
[Bug]: Waypoint breaks Cardkb and Tdeck left and right buttons/trackball

### ISSUE THREAD

**Issue by HarukiToreda** [meshtastic/firmware#4681]
### Category

Other

### Hardware

Heltec V3

### Firmware Version

2.4.3

### Description

when someone shares a waypoint on the mesh and it shows on the screen, the left and right buttons on the cardkb and the tackball no longer work to go to the next or previous frames. Someone recently shared a waypoint and all my nodes were affected, it got fixed when the waypoint screen was removed.

**Comment by todd-herbert** [comment]
I'm pretty sure this is caused by [Screen.cpp Line 2724](https://github.com/meshtastic/firmware/blob/1ba4f6e2223d6e6f1595445add774f2e71d8b19e/src/graphics/Screen.cpp#L2724). It prevents a keyboard from scrolling between screen frames when a module frame is shown. I'd guess that this is used to allow left and right events to interact with the canned message module frame.
