### ISSUE TITLE
[Bug]: Heltec v3 +NEO 6M GPS module

### ISSUE THREAD

**Issue by mb106429** [meshtastic/firmware#5094]
### Category

Hardware Compatibility

### Hardware

Heltec V3

### Firmware Version

latest Alpha oct2024

### Description

Perfect coordinates showing on the oled. In meshtastic app there is a large blue circle and the centre of which is a mile away from where I am with different coordinates when you tap on the map pin. Sometimes the circle goes and the pin moves to the correct place but this is rare. I have rebooted and reinstalled bothe the app on my phone and the heltec firmware several times. I chave changed the update settings for frequency and distance etc... I think the coordinates on the map should be the same as on the oled

### Relevant log output

```Shell
The debug output doesn't seem to include any coordinates data
```

**Comment by fifieldt** [comment]
Hi @mb106429 , thanks for using meshtastic!

There have been some firmware changes recently and now GPS location defaults to a lower level of precision. If you go into position settings and channel settings on the app you can set the precision to a higher level. https://meshtastic.org/docs/configuration/radio/channels/#position-precision

This change was made to preserve people's privacy by default. You'll always see a precise location on the screen since it's likely to be you viewing the screen :) The data on the map shows what's sent to the mesh.
