### ISSUE TITLE
[Feature Request]: Add an option to auto-delete stale nodes (inactive for x days)

### ISSUE THREAD

**Issue by JurajKubrican** [meshtastic/firmware#5283]
### Platform

Cross-Platform

### Description

This relates to https://github.com/meshtastic/firmware/issues/5282 node db full 

I believe a node can actually benefit from having a smaller node db.

On initial connection to the node, all nodes are being sent over a connection that can be slow/unreliable. this can lead to a slow / frustrating experience.

I believe adding an option to auto delete nodes that have not been heard for x days default week might improve the overall experience.

A similar feature has been added to the MeshSense SW which allows you to delete inactive nodes.

**Comment by garthvh** [comment]
You can already exclude the node db when connecting and there is an iss for a node only call https://github.com/meshtastic/firmware/issues/4564

**Comment by heeplr** [comment]
@b8b8 Wouldn't that force re-exchanging keys unnecessarily when they come back into range

That's also true when deleting all nodes after "node db is full". Less re-exchanges when only purging "stale" nodes.

@As a hypothetical, if I start up a device after months of inactivity, a TTL expiration for nodes in my NodeDB could cause all of my nodes to disappear.

That's exactly what should happen because most of the mobile nodes are gone forever.
Also the purge could be delayed to run only after a few hours uptime so any node that's still in range will have refreshed it's TTL by then.
